-- Migration 31 — Banque de micro-questions BLOC 2 (seed autoritaire)
-- À insérer tel quel. Ne jamais reformuler les questions ni les options.
-- ON CONFLICT (question_key) DO NOTHING : idempotent.

INSERT INTO discovery_questions (
  question_key, dimension, subdimension, question_text, question_type, options,
  trigger_condition, updates_dimensions, updates_must_have, updates_deal_breakers,
  profile_output_impact, sort_order, target, statut
) VALUES

-- ── 1. LANGAGE D'ATTENTION ────────────────────────────────────────────────────

('attention.detail_quality', 'attention', 'detail_quality',
 'Quand tu dis aimer les petites attentions, qu''est-ce qui te touche le plus concrètement ?',
 'chips_multi',
 '[{"label":"Que l''autre se souvienne d''un détail que j''ai dit","value":"remembers_details"},{"label":"Qu''il/elle anticipe un besoin avant que je demande","value":"anticipates_needs"},{"label":"Qu''il/elle fasse quelque chose de simple mais régulier","value":"regular_simple"},{"label":"Qu''il/elle choisisse quelque chose uniquement pour moi","value":"chosen_only_for_me"},{"label":"Qu''il/elle pense à moi dans un moment ordinaire","value":"thinks_in_ordinary"},{"label":"Qu''il/elle m''enlève une petite charge du quotidien","value":"relieves_daily_charge"}]',
 'petites_attentions selected or detected',
 ARRAY['detail_memory_importance','anticipation_importance','regularity_preference','personalization_requirement','daily_life_attention','charge_mental_relief'],
 false, false,
 'Prioriser les attentions discrètes, régulières, personnelles, liées au quotidien, plutôt que les grands gestes génériques.',
 150, 'self', 'active'),

('attention.words_quality', 'attention', 'words_quality',
 'Les mots qui te touchent vraiment sont plutôt…',
 'chips_multi',
 '[{"label":"Très précis sur ce que l''autre aime chez moi","value":"precise_about_me"},{"label":"Courts mais sincères","value":"short_sincere"},{"label":"Longs et détaillés","value":"long_detailed"},{"label":"Écrits pour que je puisse les relire","value":"written_to_reread"},{"label":"Dits spontanément","value":"spontaneous"},{"label":"Liés à un effort qu''on a remarqué","value":"effort_recognition"},{"label":"Liés à une période difficile","value":"support_in_hard_times"}]',
 'mots selected or detected',
 ARRAY['message_style','written_words_preference','recognition_need','effort_recognition_need','emotional_support_words'],
 false, false,
 'Adapter les cartes, lettres, messages d''excuse, messages de soutien, messages d''anniversaire.',
 160, 'self', 'active'),

('attention.words_avoid', 'attention', 'words_avoid',
 'Les mots peuvent tomber à plat quand…',
 'chips_multi',
 '[{"label":"Ils sont trop génériques","value":"too_generic"},{"label":"Ils arrivent trop tard","value":"too_late"},{"label":"Ils ne sont pas suivis d''actes","value":"need_actions"},{"label":"Ils sont trop grandiloquents","value":"too_dramatic"},{"label":"Ils évitent le vrai sujet","value":"avoid_real_topic"},{"label":"Ils ressemblent à une formule toute faite","value":"formulaic"}]',
 'mots selected',
 ARRAY['avoid_generic_messages','words_need_actions','avoid_overdramatic_tone','avoid_delayed_words'],
 false, true,
 'Ne jamais proposer un message générique. Associer les mots à une action si nécessaire.',
 170, 'self', 'active'),

('attention.service_quality', 'attention', 'service_quality',
 'Quand quelqu''un t''aide, ce qui te touche vraiment c''est qu''il/elle…',
 'chips_multi',
 '[{"label":"Voie ce qu''il y a à faire sans que je demande","value":"proactive"},{"label":"Prenne en charge quelque chose jusqu''au bout","value":"end_to_end"},{"label":"Me libère du temps","value":"time_relief"},{"label":"Me facilite une journée compliquée","value":"day_smoothing"},{"label":"Fasse quelque chose d''utile mais avec délicatesse","value":"discreet_service"},{"label":"N''attende pas de reconnaissance immédiate","value":"no_recognition_needed"}]',
 'actes / aide concrète / service selected',
 ARRAY['proactive_help','end_to_end_help','time_relief','day_smoothing','discreet_service'],
 false, false,
 'Prioriser garde d''enfant, repas livré, ménage, réservation, organisation complète, tâches prises en charge.',
 180, 'self', 'active'),

('attention.gift_precision', 'attention', 'gift_precision',
 'Un cadeau pensé pour toi doit surtout montrer que…',
 'chips_multi',
 '[{"label":"L''autre connaît mes goûts","value":"knows_taste"},{"label":"L''autre a retenu quelque chose que j''ai dit","value":"remembered_signal"},{"label":"L''autre a cherché quelque chose de précis","value":"search_effort"},{"label":"L''objet a une histoire ou un sens","value":"symbolic_object"},{"label":"Le cadeau n''aurait pas pu être offert à n''importe qui","value":"non_generic"},{"label":"La qualité est au rendez-vous","value":"quality"}]',
 'cadeau choisi / cadeau symbolique selected',
 ARRAY['taste_accuracy_requirement','remembered_signal_importance','search_effort_importance','symbolic_object_preference','non_generic_requirement','quality_requirement'],
 true, false,
 NULL, 190, 'self', 'active'),

('attention.experience_quality', 'attention', 'experience_quality',
 'Une expérience réussie pour toi, c''est surtout…',
 'chips_multi',
 '[{"label":"Un moment qui sort du quotidien","value":"escape"},{"label":"Un lieu vraiment beau","value":"beautiful_place"},{"label":"Une organisation fluide","value":"logistics_smooth"},{"label":"Une émotion forte","value":"strong_emotion"},{"label":"Une découverte","value":"discovery"},{"label":"Un moment de qualité à deux","value":"quality_time"},{"label":"Une parenthèse où je n''ai rien à gérer","value":"no_logistics"}]',
 'experience selected',
 ARRAY['experience_escape','beautiful_place_importance','logistics_smoothness','emotional_intensity_experience','discovery_preference','quality_time_preference','no_logistics_need'],
 false, false,
 NULL, 200, 'self', 'active'),

-- ── 2. CADEAUX / OBJETS / QUALITÉ ─────────────────────────────────────────────

('gifts.object_quality', 'gifts', 'object_quality',
 'Quand on t''offre un objet, qu''est-ce qui fait la différence entre "sympa" et "vraiment réussi" ?',
 'chips_multi',
 '[{"label":"La qualité de la matière","value":"material_quality"},{"label":"La marque ou le créateur","value":"brand"},{"label":"Le fait que ce soit exactement mon style","value":"my_style"},{"label":"Le fait que ce soit rare ou difficile à trouver","value":"rare"},{"label":"Le fait que ce soit personnalisé","value":"personalized"},{"label":"Le fait que ce soit utile au quotidien","value":"useful"},{"label":"Le fait que ça ait une histoire","value":"has_story"}]',
 'cadeau matériel selected',
 ARRAY['object_quality_driver','brand_importance','style_precision_required','rarity_preference','personalization_preference','utility_preference','story_value'],
 true, false,
 NULL, 210, 'self', 'active'),

('gifts.risky_categories', 'gifts', 'risky_categories',
 'Quel type d''objet est le plus risqué à t''offrir sans te demander ?',
 'chips_multi',
 '[{"label":"Vêtement","value":"clothing"},{"label":"Bijou","value":"jewelry"},{"label":"Parfum","value":"perfume"},{"label":"Décoration","value":"decoration"},{"label":"Livre","value":"book"},{"label":"Beauté / skincare","value":"beauty"},{"label":"Tech","value":"tech"},{"label":"Accessoire","value":"accessory"},{"label":"Tout objet trop personnel est risqué","value":"all_personal"},{"label":"Rien, je suis assez facile","value":"none"}]',
 'objet / mode / beauté / bijou / déco detected',
 ARRAY['risky_categories','admin_validation_required_by_category','prefer_choose_together'],
 false, true,
 'Si catégorie risquée, proposer carte cadeau, expérience, choix accompagné, validation par pilote, ou demander plus d''informations.',
 220, 'self', 'active'),

('gifts.quality_non_negotiable', 'gifts', 'quality_non_negotiable',
 'Dans quelles catégories la qualité est non négociable pour toi ?',
 'chips_multi',
 '[{"label":"Hôtel","value":"hotel"},{"label":"Restaurant","value":"restaurant"},{"label":"Bijou","value":"jewelry"},{"label":"Vêtement","value":"clothing"},{"label":"Sac / maroquinerie","value":"bag"},{"label":"Parfum","value":"perfume"},{"label":"Beauté / soin","value":"beauty"},{"label":"Literie","value":"bedding"},{"label":"Spa / massage","value":"spa"},{"label":"Alimentaire","value":"food"},{"label":"Je suis assez flexible","value":"flexible"}]',
 'qualité / standing / raffinement detected',
 ARRAY['quality_must_have_by_category','premium_threshold_by_category','avoid_low_quality_by_category'],
 true, false,
 'Exclure les options moyennes dans les catégories sélectionnées.',
 230, 'self', 'active'),

('gifts.impersonal_definition', 'gifts', 'impersonal_definition',
 'Pour toi, un cadeau devient impersonnel quand…',
 'chips_multi',
 '[{"label":"Il pourrait être offert à n''importe qui","value":"could_be_for_anyone"},{"label":"Il ne tient pas compte de mon style","value":"ignores_style"},{"label":"Il est acheté à la dernière minute","value":"last_minute"},{"label":"Il vient d''une enseigne trop générique","value":"generic_store"},{"label":"Il n''a aucun mot ou contexte","value":"no_note"},{"label":"Il ne correspond pas à ce que je vis en ce moment","value":"not_current"}]',
 'cadeau impersonnel mentioned in avoidances',
 ARRAY['impersonal_gift_definition','requires_contextualization','requires_personal_note','avoid_generic_supplier'],
 false, true,
 NULL, 240, 'self', 'active'),

-- ── 3. RESTAURANTS ────────────────────────────────────────────────────────────

('food.deal_breakers', 'food', 'deal_breakers',
 'Pour un restaurant surprise, qu''est-ce qui peut vraiment gâcher l''expérience ?',
 'chips_multi',
 '[{"label":"Trop bruyant","value":"too_loud"},{"label":"Tables trop serrées","value":"too_crowded"},{"label":"Service froid","value":"cold_service"},{"label":"Cuisine moyenne","value":"average_food"},{"label":"Lieu sans charme","value":"no_charm"},{"label":"Mauvaise lumière","value":"bad_light"},{"label":"Trop prétentieux","value":"too_pretentious"},{"label":"Trop simple / cheap","value":"too_cheap"},{"label":"Trop loin","value":"too_far"},{"label":"Menu trop limité","value":"limited_menu"},{"label":"Mauvais rapport qualité-prix","value":"bad_value"}]',
 'gastronomie / restaurant / belles tables selected',
 ARRAY['restaurant_deal_breakers','restaurant_selection_rules','ambience_avoidance','min_quality_threshold'],
 false, true,
 NULL, 250, 'self', 'active'),

('food.success_driver', 'food', 'success_driver',
 'Un restaurant réussi pour toi, c''est d''abord…',
 'chips_single',
 '[{"label":"La cuisine","value":"cuisine"},{"label":"L''ambiance","value":"ambiance"},{"label":"Le service","value":"service"},{"label":"Le lieu","value":"venue"},{"label":"La vue","value":"view"},{"label":"Le confort","value":"comfort"},{"label":"La rareté de l''adresse","value":"rarity"},{"label":"Le fait que ce soit vivant","value":"lively"},{"label":"Le fait que ce soit intime","value":"intimate"}]',
 'restaurant selected',
 ARRAY['restaurant_success_driver','restaurant_search_priority'],
 true, false,
 'Détermine si Candice privilégie note, ambiance, vue, intimité, rareté, service ou cuisine.',
 260, 'self', 'active'),

('food.cuisine_preferences', 'food', 'cuisine_preferences',
 'Côté cuisine, ce qui te ferait vraiment plaisir en ce moment serait plutôt…',
 'chips_multi',
 '[{"label":"Français","value":"french"},{"label":"Italien","value":"italian"},{"label":"Japonais","value":"japanese"},{"label":"Libanais","value":"lebanese"},{"label":"Méditerranéen","value":"mediterranean"},{"label":"Thaï","value":"thai"},{"label":"Indien","value":"indian"},{"label":"Mexicain","value":"mexican"},{"label":"Tapas","value":"tapas"},{"label":"Fruits de mer","value":"seafood"},{"label":"Pâtisserie / tea time","value":"pastry"},{"label":"Cuisine végétale","value":"plant_based"},{"label":"Je préfère être surpris·e si c''est très bon","value":"surprise_me"}]',
 'cuisine du monde / gastronomie / restaurant selected',
 ARRAY['cuisine_preferences','restaurant_dynamic_search_filters'],
 false, false,
 NULL, 270, 'self', 'active'),

('food.reference_address', 'food', 'reference_address',
 'Donne une adresse que tu adores, même simple. Candice s''en servira comme référence de goût.',
 'text', NULL,
 'restaurants aimés non renseignés',
 ARRAY['favorite_restaurants','restaurant_style_reference'],
 false, false,
 NULL, 280, 'self', 'active'),

('food.reco_strategy', 'food', 'reco_strategy',
 'Pour une recommandation restaurant, Candice doit plutôt viser…',
 'chips_single',
 '[{"label":"Très bien noté, même simple","value":"well_rated"},{"label":"Beau lieu avant tout","value":"beautiful_venue"},{"label":"Cuisine excellente avant tout","value":"excellent_cuisine"},{"label":"Ambiance vivante","value":"lively"},{"label":"Adresse chic","value":"chic"},{"label":"Adresse cachée","value":"hidden"},{"label":"Valeur sûre","value":"safe_bet"},{"label":"Surprise originale","value":"original_surprise"}]',
 'restaurants score fort',
 ARRAY['restaurant_reco_strategy'],
 false, false,
 NULL, 290, 'self', 'active'),

-- ── 4. VOYAGES ────────────────────────────────────────────────────────────────

('travel.hotel_criteria', 'travel', 'hotel_criteria',
 'Quand tu parles d''un "bel endroit", qu''est-ce qui compte vraiment ?',
 'chips_multi',
 '[{"label":"Literie parfaite","value":"perfect_bedding"},{"label":"Décoration / architecture","value":"decor"},{"label":"Service impeccable","value":"service"},{"label":"Spa / piscine","value":"spa"},{"label":"Vue","value":"view"},{"label":"Calme","value":"quiet"},{"label":"Chambre spacieuse","value":"spacious"},{"label":"Très bon restaurant","value":"great_restaurant"},{"label":"Emplacement idéal","value":"location"},{"label":"Atmosphère intime","value":"intimate"},{"label":"Palace / grand luxe","value":"palace"},{"label":"Boutique-hôtel de charme","value":"boutique"}]',
 'voyage / week-end / hôtel / luxe detected',
 ARRAY['hotel_success_drivers','hotel_must_have','hotel_style_preference','premium_threshold_hotel'],
 true, false,
 NULL, 300, 'self', 'active'),

('travel.deal_breakers', 'travel', 'deal_breakers',
 'Ce qui peut vraiment gâcher un week-end pour toi…',
 'chips_multi',
 '[{"label":"Mauvaise literie","value":"bad_bedding"},{"label":"Hôtel moyen","value":"average_hotel"},{"label":"Trop de route","value":"too_much_driving"},{"label":"Trop de logistique","value":"too_much_logistics"},{"label":"Lieu sans charme","value":"no_charm"},{"label":"Programme trop chargé","value":"overloaded_schedule"},{"label":"Mauvaise nourriture","value":"bad_food"},{"label":"Trop rustique","value":"too_rustic"},{"label":"Pas assez confortable","value":"not_comfortable"},{"label":"Trop isolé","value":"too_isolated"},{"label":"Trop touristique","value":"too_touristy"},{"label":"Pas assez premium","value":"not_premium"}]',
 'voyage / week-end detected',
 ARRAY['travel_deal_breakers','avoid_rustic','avoid_average_hotel','no_logistics_need','max_program_density'],
 false, true,
 NULL, 310, 'self', 'active'),

('travel.hotel_standard', 'travel', 'hotel_standard',
 'Pour un week-end surprise, ton niveau de confort minimum serait plutôt…',
 'chips_single',
 '[{"label":"Peu importe si l''expérience est forte","value":"experience_first"},{"label":"Hôtel confortable et propre","value":"comfortable"},{"label":"Très bon 4 étoiles","value":"four_stars"},{"label":"5 étoiles si possible","value":"five_stars"},{"label":"Boutique-hôtel très soigné","value":"boutique"},{"label":"Palace / très luxe pour les grandes occasions","value":"palace"}]',
 'hôtel / confort / luxe detected',
 ARRAY['hotel_minimum_standard','budget_expectation','premium_threshold_hotel'],
 true, false,
 NULL, 320, 'self', 'active'),

('travel.distance_tolerance', 'travel', 'distance_tolerance',
 'Pour une surprise week-end, tu es prêt·e à faire combien de trajet ?',
 'chips_single',
 '[{"label":"Moins d''1h","value":"under_1h"},{"label":"1 à 2h","value":"1_2h"},{"label":"2 à 3h","value":"2_3h"},{"label":"3 à 5h","value":"3_5h"},{"label":"Train OK","value":"train_ok"},{"label":"Avion OK","value":"plane_ok"},{"label":"Ça dépend si le lieu vaut vraiment le coup","value":"depends"}]',
 'week-end / voyage surprise detected',
 ARRAY['travel_distance_tolerance','logistics_constraints'],
 false, false,
 NULL, 330, 'self', 'active'),

('dreams.destination', 'dreams', 'destination',
 'Une destination, un hôtel ou une expérience dont tu rêves en ce moment ?',
 'text', NULL,
 'destination rêve non renseignée',
 ARRAY['destination','hotel','experience_type','wishlist_high_priority'],
 false, false,
 NULL, 340, 'self', 'active'),

-- ── 5. LECTURE ────────────────────────────────────────────────────────────────

('hobbies.book_conditions', 'hobbies', 'book_conditions',
 'Un livre en cadeau peut vraiment te plaire si…',
 'chips_multi',
 '[{"label":"C''est un auteur que j''aime déjà","value":"known_author"},{"label":"C''est une très belle édition","value":"beautiful_edition"},{"label":"C''est recommandé avec un mot personnel","value":"with_personal_note"},{"label":"C''est un livre qui correspond à une période de ma vie","value":"matches_life_period"},{"label":"C''est une BD / un roman graphique choisi avec soin","value":"graphic_novel"},{"label":"C''est un livre rare ou signé","value":"rare_signed"},{"label":"C''est plutôt risqué, je préfère choisir moi-même","value":"prefer_choose"}]',
 'lecture / livre / BD detected',
 ARRAY['book_gift_conditions','author_importance','beautiful_edition_preference','personal_note_required','book_risk_score','graphic_novel_relevance'],
 false, false,
 NULL, 350, 'self', 'active'),

('hobbies.book_avoidance', 'hobbies', 'book_avoidance',
 'Un livre risque de tomber à plat si…',
 'chips_multi',
 '[{"label":"Il est trop \"développement personnel\" évident","value":"too_self_help"},{"label":"Il est trop intellectuel","value":"too_intellectual"},{"label":"Il est trop léger","value":"too_light"},{"label":"Il ne correspond pas à mon style","value":"wrong_style"},{"label":"Il est choisi parce qu''il est à la mode","value":"too_trendy"},{"label":"Il ressemble à une leçon déguisée","value":"moralizing"},{"label":"Il parle d''un sujet sensible","value":"sensitive_topic"}]',
 'lecture detected',
 ARRAY['book_avoidance','sensitive_topics','avoid_trendy_books','avoid_moralizing_gifts'],
 false, true,
 NULL, 360, 'self', 'active'),

('hobbies.book_reference', 'hobbies', 'book_reference',
 'Cite un auteur, une autrice, une BD ou un livre que tu aimes vraiment.',
 'text', NULL,
 'auteur / livre préféré non renseigné',
 ARRAY['author','title','genre','format','universe'],
 false, false,
 'Permet à Claude de chercher les dernières sorties, belles éditions, rencontres, coffrets, adaptations, expériences culturelles associées.',
 370, 'self', 'active'),

-- ── 6. MODE / STYLE / BIJOUX ──────────────────────────────────────────────────

('style.fashion_gift_risk', 'style', 'fashion_gift_risk',
 'Si quelqu''un veut t''offrir quelque chose lié à la mode, le moins risqué serait…',
 'chips_single',
 '[{"label":"M''emmener choisir","value":"choose_together"},{"label":"Carte cadeau d''une marque que j''aime","value":"gift_card"},{"label":"Accessoire","value":"accessory"},{"label":"Bijou","value":"jewelry"},{"label":"Foulard / belle matière","value":"scarf"},{"label":"Sac / petite maroquinerie","value":"bag"},{"label":"Vêtement uniquement si taille et style sûrs","value":"clothing_if_sure"},{"label":"Ne pas m''offrir de mode","value":"avoid_fashion"}]',
 'mode / vêtements / marques detected',
 ARRAY['fashion_gift_risk','prefer_choose_together','safe_fashion_categories'],
 false, false,
 NULL, 380, 'self', 'active'),

('style.jewelry_style', 'style', 'jewelry_style',
 'Un bijou réussi pour toi, c''est plutôt…',
 'chips_multi',
 '[{"label":"Fin et discret","value":"delicate"},{"label":"Visible / affirmé","value":"bold"},{"label":"Doré","value":"gold"},{"label":"Argenté","value":"silver"},{"label":"Avec pierre","value":"with_stone"},{"label":"Personnalisé / gravé","value":"personalized"},{"label":"Symbolique","value":"symbolic"},{"label":"Très mode","value":"trendy"},{"label":"Intemporel","value":"timeless"},{"label":"D''une marque précise","value":"specific_brand"}]',
 'bijoux detected',
 ARRAY['jewelry_style','jewelry_material','symbolic_jewelry_preference','jewelry_brand_importance'],
 false, false,
 NULL, 390, 'self', 'active'),

('style.fashion_deal_breakers', 'style', 'fashion_deal_breakers',
 'Côté style, ce qu''il faut éviter absolument…',
 'chips_multi',
 '[{"label":"Trop classique","value":"too_classic"},{"label":"Trop cheap","value":"too_cheap"},{"label":"Trop voyant","value":"too_flashy"},{"label":"Trop discret","value":"too_discreet"},{"label":"Mauvaise matière","value":"bad_material"},{"label":"Mauvaise coupe","value":"bad_fit"},{"label":"Mauvaise taille","value":"wrong_size"},{"label":"Trop \"cadeau par défaut\"","value":"default_gift"},{"label":"Marque que je n''aime pas","value":"wrong_brand"}]',
 'mode / style detected',
 ARRAY['fashion_deal_breakers','avoid_bad_fit','avoid_bad_material','avoid_wrong_brand'],
 false, true,
 NULL, 400, 'self', 'active'),

('brands.reference_free', 'brands', 'brand_reference_free',
 'Cite 3 marques ou créateurs que tu aimes vraiment — même très différents.',
 'text', NULL,
 'marques aimées non détaillées',
 ARRAY['brands','gamme','style','aesthetic'],
 false, false,
 NULL, 410, 'self', 'active'),

-- ── 7. BEAUTÉ / PARFUM / SOIN ─────────────────────────────────────────────────

('fragrance.perfume_risk', 'fragrance', 'perfume_risk',
 'Pour un parfum, tu préfères…',
 'chips_single',
 '[{"label":"Je préfère choisir moi-même","value":"choose_myself"},{"label":"On peut m''en offrir si on connaît mes goûts","value":"if_knows_taste"},{"label":"Seulement une marque que j''aime","value":"known_brand_only"},{"label":"Plutôt bougie / parfum d''intérieur","value":"home_fragrance"},{"label":"Je n''aime pas recevoir de parfum","value":"avoid"}]',
 'parfum / beauté detected',
 ARRAY['perfume_gift_risk','perfume_preference','home_fragrance_preference'],
 false, false,
 NULL, 420, 'self', 'active'),

('fragrance.beauty_gift', 'fragrance', 'beauty_gift',
 'Un cadeau beauté réussi, c''est plutôt…',
 'chips_multi',
 '[{"label":"Une marque experte","value":"expert_brand"},{"label":"Une marque sensorielle","value":"sensory_brand"},{"label":"Un soin en institut","value":"institute_care"},{"label":"Un massage","value":"massage"},{"label":"Un produit que j''utilise déjà","value":"known_product"},{"label":"Un produit découverte","value":"discovery_product"},{"label":"Un coffret premium","value":"premium_set"},{"label":"Je préfère éviter","value":"avoid"}]',
 'beauté / soin detected',
 ARRAY['beauty_gift_strategy','skincare_risk','spa_preference','known_product_preference'],
 false, false,
 NULL, 430, 'self', 'active'),

('fragrance.scent_deal_breakers', 'fragrance', 'scent_deal_breakers',
 'Les odeurs à éviter absolument pour toi…',
 'chips_multi',
 '[{"label":"Trop sucré","value":"too_sweet"},{"label":"Patchouli","value":"patchouli"},{"label":"Trop floral","value":"too_floral"},{"label":"Trop fort","value":"too_strong"},{"label":"Trop boisé","value":"too_woody"},{"label":"Vanille","value":"vanilla"},{"label":"Encens","value":"incense"},{"label":"Musc","value":"musk"},{"label":"Je ne sais pas","value":"unknown"}]',
 'odeurs / parfums detected',
 ARRAY['scent_deal_breakers'],
 false, true,
 NULL, 440, 'self', 'active'),

('brands.beauty_reference', 'brands', 'beauty_brands',
 'Une marque beauté, parfum ou soin que tu aimes vraiment ?',
 'text', NULL,
 'marques beauté non renseignées',
 ARRAY['brand','category','gamme'],
 false, false,
 NULL, 450, 'self', 'active'),

-- ── 8. SURPRISES ──────────────────────────────────────────────────────────────

('surprises.conditions', 'surprises', 'conditions',
 'Tu peux aimer une surprise si…',
 'chips_multi',
 '[{"label":"Je connais au moins l''horaire","value":"know_schedule"},{"label":"Je sais comment m''habiller","value":"know_dress_code"},{"label":"Je sais combien de temps ça dure","value":"know_duration"},{"label":"Je peux refuser sans gêne","value":"can_decline"},{"label":"Ce n''est pas devant trop de monde","value":"not_too_public"},{"label":"C''est organisé par quelqu''un de très proche","value":"very_close_person"},{"label":"C''est très bien préparé","value":"well_prepared"}]',
 'surprise ouverte / partielle detected',
 ARRAY['surprise_conditions','surprise_logistics_requirements','surprise_social_boundary'],
 false, false,
 NULL, 460, 'self', 'active'),

('surprises.briefing_needed', 'surprises', 'briefing_needed',
 'Avant une surprise, tu as besoin de savoir au minimum…',
 'chips_multi',
 '[{"label":"L''heure","value":"time"},{"label":"La tenue","value":"dress_code"},{"label":"La durée","value":"duration"},{"label":"Le lieu approximatif","value":"approx_location"},{"label":"Si je dois prévoir une garde d''enfant","value":"childcare"},{"label":"Si c''est intime ou social","value":"intimate_or_social"},{"label":"Rien, j''aime la surprise totale","value":"total_surprise"}]',
 'surprise detected',
 ARRAY['surprise_briefing_needed'],
 false, false,
 NULL, 470, 'self', 'active'),

('surprises.deal_breakers', 'surprises', 'deal_breakers',
 'La surprise à éviter absolument pour toi, ce serait…',
 'chips_multi',
 '[{"label":"Une surprise en public","value":"public"},{"label":"Une surprise avec trop de monde","value":"too_many_people"},{"label":"Une surprise qui change mon planning","value":"changes_plans"},{"label":"Une surprise où je ne sais pas comment m''habiller","value":"no_dress_code"},{"label":"Une surprise trop chère","value":"too_expensive"},{"label":"Une surprise trop intime","value":"too_intimate"},{"label":"Une surprise qui ne me ressemble pas","value":"not_me"}]',
 'surprise négative ou prudente detected',
 ARRAY['surprise_deal_breakers'],
 false, true,
 NULL, 480, 'self', 'active'),

-- ── 9. ORGANISATION / CHARGE MENTALE ──────────────────────────────────────────

('practical.logistics_relief', 'practical', 'logistics_relief',
 'Dans une attention, ce qui t''allège vraiment, c''est qu''on gère…',
 'chips_multi',
 '[{"label":"La réservation","value":"reservation"},{"label":"Le transport","value":"transport"},{"label":"Les enfants","value":"children"},{"label":"Le repas","value":"meal"},{"label":"Les courses","value":"groceries"},{"label":"Le ménage","value":"cleaning"},{"label":"Le timing","value":"timing"},{"label":"La décision","value":"decision"},{"label":"Les détails pratiques","value":"practical_details"},{"label":"Le suivi après","value":"follow_up"}]',
 'charge mentale / fatigue / besoin d''organisation detected',
 ARRAY['logistics_relief_targets','no_logistics_need','support_attention_candidates'],
 false, false,
 NULL, 490, 'self', 'active'),

('practical.control_delegation', 'practical', 'control_delegation',
 'Quand quelqu''un organise pour toi, tu préfères…',
 'chips_single',
 '[{"label":"Qu''il décide vraiment","value":"decide_all"},{"label":"Qu''il me propose 2 options","value":"two_options"},{"label":"Qu''il me laisse valider les détails","value":"validate_details"},{"label":"Qu''il gère tout sauf la date","value":"all_except_date"},{"label":"Qu''il me surprenne mais me rassure","value":"surprise_but_reassure"},{"label":"Qu''il ne décide pas à ma place","value":"no_decide_for_me"}]',
 'aime qu''on organise / surprise / charge mentale detected',
 ARRAY['control_vs_delegation','decision_relief','validation_need'],
 false, false,
 NULL, 500, 'self', 'active'),

-- ── 10. CONFLIT / RÉPARATION ──────────────────────────────────────────────────

('conflicts.repair_strategy', 'conflicts', 'repair_strategy',
 'Après une tension, ce qui aide vraiment à réparer pour toi, c''est…',
 'chips_multi',
 '[{"label":"Des excuses précises","value":"precise_apology"},{"label":"Un message écrit","value":"written_message"},{"label":"Une discussion calme","value":"calm_discussion"},{"label":"Une preuve que l''autre a compris","value":"proof_understood"},{"label":"Un geste concret","value":"concrete_gesture"},{"label":"Un moment ensemble","value":"time_together"},{"label":"Un peu de temps","value":"time_alone"},{"label":"Pas de cadeau, surtout une vraie parole","value":"words_not_gift"}]',
 'conflit / réparation non précisé',
 ARRAY['conflict_repair_strategy','apology_style','repair_attention_allowed'],
 false, false,
 NULL, 510, 'self', 'active'),

('conflicts.repair_avoid', 'conflicts', 'repair_avoid',
 'Après une dispute, ce qui serait maladroit…',
 'chips_multi',
 '[{"label":"Faire comme si rien ne s''était passé","value":"ignore_conflict"},{"label":"Offrir un cadeau sans parler","value":"gift_without_words"},{"label":"Mettre de l''humour trop vite","value":"humor_too_soon"},{"label":"Insister alors que j''ai besoin d''espace","value":"insist_when_need_space"},{"label":"Dramatiser","value":"dramatize"},{"label":"Se justifier","value":"justify"},{"label":"Attendre trop longtemps","value":"wait_too_long"}]',
 'conflit / réparation non précisé',
 ARRAY['conflict_avoidance_rules','post_conflict_forbidden_actions'],
 false, true,
 NULL, 520, 'self', 'active'),

-- ── 11. SENSORIELLES ──────────────────────────────────────────────────────────

('style.material_preferences', 'style', 'material_preferences',
 'Les matières qui te donnent vraiment une impression de qualité…',
 'chips_multi',
 '[{"label":"Cachemire","value":"cashmere"},{"label":"Soie","value":"silk"},{"label":"Cuir","value":"leather"},{"label":"Daim","value":"suede"},{"label":"Lin","value":"linen"},{"label":"Coton épais","value":"thick_cotton"},{"label":"Laine mérinos","value":"merino"},{"label":"Céramique","value":"ceramic"},{"label":"Bois","value":"wood"},{"label":"Verre soufflé","value":"blown_glass"},{"label":"Métal doré","value":"gold_metal"},{"label":"Pierre naturelle","value":"natural_stone"}]',
 'mode / déco / beauté / matières detected',
 ARRAY['material_preferences','premium_material_signals'],
 true, false,
 NULL, 530, 'self', 'active'),

('style.material_avoidance', 'style', 'material_avoidance',
 'Les matières qui peuvent te déplaire…',
 'chips_multi',
 '[{"label":"Synthétique","value":"synthetic"},{"label":"Laine qui gratte","value":"scratchy_wool"},{"label":"Polyester","value":"polyester"},{"label":"Matière trop rigide","value":"too_rigid"},{"label":"Matière trop fragile","value":"too_fragile"},{"label":"Faux cuir","value":"faux_leather"},{"label":"Fourrure","value":"fur"},{"label":"Plastique","value":"plastic"},{"label":"Je ne sais pas","value":"unknown"}]',
 'mode / déco / matières detected',
 ARRAY['material_avoidance'],
 false, true,
 NULL, 540, 'self', 'active'),

('style.color_safe', 'style', 'color_safe',
 'Si on t''offre un objet, un vêtement ou un accessoire, les couleurs les plus sûres sont…',
 'chips_multi',
 '[{"label":"Noir","value":"black"},{"label":"Blanc","value":"white"},{"label":"Beige","value":"beige"},{"label":"Bleu ciel","value":"light_blue"},{"label":"Marine","value":"navy"},{"label":"Vert","value":"green"},{"label":"Rouge","value":"red"},{"label":"Rose pâle","value":"pale_pink"},{"label":"Doré","value":"gold"},{"label":"Argenté","value":"silver"},{"label":"Tons neutres","value":"neutral_tones"},{"label":"Couleurs fortes","value":"bold_colors"},{"label":"Je préfère choisir","value":"prefer_choose"}]',
 'mode / déco / objet detected',
 ARRAY['color_safe_choices','color_avoidance_if_free_text'],
 false, false,
 NULL, 550, 'self', 'active'),

-- ── 12. DÉCO / MAISON ─────────────────────────────────────────────────────────

('hobbies.home_gift_safe', 'hobbies', 'home_gift_safe',
 'Pour la maison, ce qui est le moins risqué à t''offrir…',
 'chips_single',
 '[{"label":"Bougie / parfum d''intérieur","value":"candle"},{"label":"Art de la table","value":"tableware"},{"label":"Linge de maison","value":"linen"},{"label":"Beau livre","value":"coffee_table_book"},{"label":"Petit objet design","value":"design_object"},{"label":"Plante","value":"plant"},{"label":"Céramique","value":"ceramic"},{"label":"Rien, je préfère choisir moi-même","value":"prefer_choose"}]',
 'déco / maison detected',
 ARRAY['home_gift_safe_categories','home_gift_risk'],
 false, false,
 NULL, 560, 'self', 'active'),

('hobbies.home_deal_breakers', 'hobbies', 'home_deal_breakers',
 'En déco, ce qui peut vite tomber à côté pour toi…',
 'chips_multi',
 '[{"label":"Objet trop kitsch","value":"too_kitsch"},{"label":"Mauvaise couleur","value":"bad_color"},{"label":"Mauvaise matière","value":"bad_material"},{"label":"Objet trop imposant","value":"too_imposing"},{"label":"Style trop froid","value":"too_cold"},{"label":"Style trop rustique","value":"too_rustic"},{"label":"Objet sans utilité","value":"useless"},{"label":"Cadeau qui encombre","value":"clutters"}]',
 'déco / maison detected',
 ARRAY['home_decor_deal_breakers'],
 false, true,
 NULL, 570, 'self', 'active'),

-- ── 13. SPORT / BIEN-ÊTRE ─────────────────────────────────────────────────────

('hobbies.wellness_gift', 'hobbies', 'wellness_gift',
 'Une attention bien-être réussie pour toi, c''est plutôt…',
 'chips_multi',
 '[{"label":"Massage","value":"massage"},{"label":"Spa","value":"spa"},{"label":"Cours privé","value":"private_class"},{"label":"Retraite","value":"retreat"},{"label":"Moment de calme","value":"quiet_time"},{"label":"Accessoire de qualité","value":"quality_accessory"},{"label":"Abonnement","value":"subscription"},{"label":"Expérience douce","value":"gentle_experience"},{"label":"Je préfère éviter les cadeaux bien-être","value":"avoid"}]',
 'sport / bien-être detected',
 ARRAY['wellness_gift_strategy','spa_preference','massage_preference','retreat_interest'],
 false, false,
 NULL, 580, 'self', 'active'),

('hobbies.sport_risk', 'hobbies', 'sport_risk',
 'Un cadeau sport est risqué si…',
 'chips_multi',
 '[{"label":"Il n''est pas adapté à ma pratique","value":"wrong_practice"},{"label":"Il est trop technique","value":"too_technical"},{"label":"Il est trop bas de gamme","value":"low_quality"},{"label":"Il suppose que je veux performer","value":"performance_assumption"},{"label":"Il touche au corps / au poids","value":"body_related"},{"label":"Il est choisi sans connaître mes habitudes","value":"unknown_habits"},{"label":"Je préfère choisir moi-même","value":"prefer_choose"}]',
 'sport detected',
 ARRAY['sport_gift_risks','avoid_body_related_gifts'],
 false, true,
 NULL, 590, 'self', 'active'),

-- ── 14. CULTURE ───────────────────────────────────────────────────────────────

('hobbies.culture_success', 'hobbies', 'culture_success',
 'Une sortie culturelle réussie pour toi, c''est surtout…',
 'chips_multi',
 '[{"label":"Une très belle œuvre","value":"great_artwork"},{"label":"Un lieu magnifique","value":"beautiful_venue"},{"label":"Une émotion forte","value":"strong_emotion"},{"label":"Une découverte","value":"discovery"},{"label":"Un moment élégant","value":"elegant"},{"label":"Une sortie facile à organiser","value":"easy_logistics"},{"label":"Une discussion après","value":"discussion_after"},{"label":"Un événement rare","value":"rare_event"}]',
 'culture / art detected',
 ARRAY['culture_success_driver','cultural_event_recommendation_rules'],
 false, false,
 NULL, 600, 'self', 'active'),

('hobbies.concert_criteria', 'hobbies', 'concert_criteria',
 'Pour un concert ou spectacle, ce qui compte le plus…',
 'chips_multi',
 '[{"label":"L''artiste","value":"artist"},{"label":"La qualité des places","value":"seat_quality"},{"label":"L''ambiance","value":"ambiance"},{"label":"Le lieu","value":"venue"},{"label":"Le confort","value":"comfort"},{"label":"Y aller avec la bonne personne","value":"right_company"},{"label":"Ne pas être trop loin / mal placé","value":"good_position"},{"label":"Le côté événement rare","value":"rare_event"}]',
 'musique / concert detected',
 ARRAY['concert_selection_rules','seat_quality_importance'],
 false, false,
 NULL, 610, 'self', 'active'),

('hobbies.artist_reference', 'hobbies', 'artist_reference',
 'Un artiste, spectacle ou lieu culturel que tu aimerais voir ?',
 'text', NULL,
 'artiste non renseigné',
 ARRAY['artist','venue','event','style'],
 false, false,
 NULL, 620, 'self', 'active'),

-- ── 15. RÊVES / WISHLIST ──────────────────────────────────────────────────────

('dreams.wish_priority', 'dreams', 'wish_priority',
 'Parmi tes envies du moment, laquelle te ferait le plus plaisir si quelqu''un t''aidait à la réaliser ?',
 'text', NULL,
 'envies / rêves du moment renseignés',
 ARRAY['dream_priority','wishlist_priority','high_emotional_impact_candidate'],
 false, false,
 NULL, 630, 'self', 'active'),

('dreams.wishlist_first', 'dreams', 'wishlist_first',
 'Une chose que tu aimerais recevoir, vivre ou faire dans les prochains mois ?',
 'text', NULL,
 'wishlist vide',
 ARRAY['object','experience','venue','brand','timing','emotional_priority'],
 false, false,
 NULL, 640, 'self', 'active'),

-- ── 16. DATES IMPORTANTES ────────────────────────────────────────────────────

('practical.important_dates', 'practical', 'important_dates_detail',
 'Y a-t-il une date que tes proches ne devraient pas oublier ?',
 'text', NULL,
 'dates importantes incomplètes',
 ARRAY['important_dates','event_trigger_engine'],
 false, false,
 NULL, 650, 'self', 'active'),

('practical.date_attention', 'practical', 'date_attention_pref',
 'Pour cette date, tu aimerais plutôt…',
 'chips_multi',
 '[{"label":"Un message","value":"message"},{"label":"Un moment ensemble","value":"time_together"},{"label":"Un cadeau","value":"gift"},{"label":"Une surprise","value":"surprise"},{"label":"Une expérience","value":"experience"},{"label":"Rien de grand, juste qu''on y pense","value":"just_remember"},{"label":"Quelque chose organisé à l''avance","value":"planned_ahead"}]',
 'date ajoutée sans préférence d''attention',
 ARRAY['event_attention_preferences'],
 false, false,
 NULL, 660, 'self', 'active')

ON CONFLICT (question_key) DO NOTHING;

-- ── Mise à jour DIMENSION_LABELS (ajout label pour nouvelles dimensions si besoin) ──
-- Les dimensions utilisées (attention, gifts, food, fragrance, travel, hobbies,
-- dreams, surprises, conflicts, practical, style, brands) sont déjà toutes
-- présentes dans discovery_questions. Pas de nouvelle dimension à ajouter.
