// ONBOARDING V15 — les 128 mappings, TRANSCRITS depuis
// docs/ontologie/onboarding-v15-mappings.md (source de données, verbatim).
//
// RÈGLE : ceci est une TRANSCRIPTION, pas une re-déduction. Aucun mapping n'est
// recalculé ici ; aucun code n'est inventé (R25). Le texte exact de la question
// et de l'option est conservé mot pour mot : il part dans la couche source
// (SourceRecord) à chaque réponse. Les chiffres de contrôle sont recalculés
// depuis CE fichier par les tests (onboarding.test.ts).
//
// Options NON actives (REMOVED_FROM_ONBOARDING_CORE / MOVED_TO_DISCOVERY_*) :
// conservées AVEC leurs mappings mais EXCLUES de tout calcul. activeOptions()
// est la SEULE porte d'entrée du scoring.
//
// ⚠ 106 et 106b sont deux options DISTINCTES (scission), même questionCode q4b.

import type { EvidenceContext, EvidenceRole } from './evidence';
import type {
  AffectionCadence,
  AffectionDirection,
  AffectionLanguageCode,
  AffectionModality,
  BehaviorContext,
  BehaviorPattern,
  ContinuumValue,
  DriverCode,
  EvidenceStrength,
  EvidenceValue,
  GuardrailCode,
  GuardrailScope,
  GuardrailSeverity,
  NeedCode,
  PreferencePath,
  ProfileConstructCode,
  SensitivityFacet,
} from './vocabulary';

/** Statut d'une option d'onboarding. Seul ACTIF alimente le scoring. */
export type OnboardingStatus =
  | 'ACTIF'
  | 'REMOVED_FROM_ONBOARDING_CORE'
  | 'MOVED_TO_DISCOVERY_FOOD'
  | 'MOVED_TO_DISCOVERY_VOYAGE';

/**
 * Valeur d'une evidence PROFILE telle qu'inscrite dans le mapping V15.
 * - Constructs directionnels : ±1 / ±2 (EvidenceValue, 0 interdit).
 * - SOCIAL_ENERGY (continuum Q5) : échelle ordinale 0..4 DÉFINITIVE (ContinuumValue),
 *   0 = recharge solitaire (extrémité), 4 = recharge sociale (extrémité). 0 n'est
 *   pas le milieu ; aucun recentrage vers −2..+2, ni ici ni plus tard. C'est la
 *   seule exception à « 0 n'est jamais une evidence ».
 */
export type OnboardingProfileValue = EvidenceValue | ContinuumValue;

/** Une evidence PROFILE produite par une option (construct + value + rôle + contexte). */
export interface OnboardingProfileEvidence {
  readonly construct: ProfileConstructCode;
  /** Sous-facette, uniquement pour PROFILE_SENSITIVITY (ex. aesthetic). */
  readonly facet?: SensitivityFacet;
  readonly value: OnboardingProfileValue;
  readonly evidence_role: EvidenceRole;
  /** 'GLOBAL' (→ GLOBAL_DIRECT) ou un chemin de domaine (→ LOCAL/CONTEXTUAL). */
  readonly context: EvidenceContext;
}

/** Une production AFFECTION_LANGUAGE (direction + modalité + rôle). */
export interface OnboardingAffection {
  readonly direction: AffectionDirection;
  readonly modality: AffectionModality;
  readonly code: AffectionLanguageCode;
  readonly evidence_role: EvidenceRole;
}

/**
 * Coefficients de scoring affectif du socle (onboarding-v15-clos §Langages affectifs).
 * Les POURCENTAGES par question expriment la QUALITÉ de l'evidence selon le stem, pas
 * l'ordre des clics — ils restent inchangés (Q1 100 %, Q4 50 %, Q2 0 %, QE vecteur séparé).
 * La pondération par rang {0:5,1:3,2:1} est RETIRÉE (lot A ter) : elle transformait une
 * information ordinale déclarée en écart cardinal que l'utilisateur n'a jamais donné.
 * La force se dérive désormais du rang par crans (rankToAffectionStrength), sans aucun
 * coefficient numérique. `affection_cadence` reste séparée de la modalité.
 */
export const AFFECTION_SCORING = {
  source: 'docs/ontologie/onboarding-v15-clos.md §Langages affectifs',
  questionWeight: { Q1: 1.0, Q4: 0.5, Q2: 0.0 },
  giveVectorSeparate: true, // QE : vecteur GIVE séparé
} as const;

/* ────────────────────────────────────────────────────────────────────────
 * ORDRE DE SÉLECTION (lot A ter, mapping-soutien-moteurs §Ordre de sélection).
 * Défaut : l'ordre de sélection N'A AUCUNE valeur sémantique — un geste d'interface
 * n'est pas une information sur la personne. SEULE EXCEPTION : une question dont
 * l'écran demande explicitement un classement. Q1 affiche un rang et dit « la première
 * compte le plus » → l'ordre y est une donnée DÉCLARÉE, conservée.
 * ──────────────────────────────────────────────────────────────────────── */

/** Invariant : par défaut, l'ordre de sélection n'est jamais sémantique. */
export const SELECTION_ORDER_IS_SEMANTIC = false;

/** Les seules questions où l'écran demande explicitement un classement (exception déclarée). */
export const QUESTIONS_WITH_EXPLICIT_RANKING = ['q1'] as const;

/** L'ordre de sélection porte-t-il une information pour cette question ? */
export function selectionOrderMatters(questionCode: string): boolean {
  return (QUESTIONS_WITH_EXPLICIT_RANKING as readonly string[]).includes(questionCode);
}

/**
 * Force d'une evidence affective d'après son RANG déclaré (Q1 uniquement).
 * Remplace le rankWeight 5/3/1 : PAS de pondération numérique, le rang choisit
 * directement un cran de EvidenceStrength, et rien d'autre.
 *   rang 1 → strong · rang 2 → strong · rang 3 → moderate
 * R6 : plusieurs modalités affectives peuvent être fortes simultanément.
 */
export function rankToAffectionStrength(rank: 1 | 2 | 3): EvidenceStrength {
  return rank === 3 ? 'moderate' : 'strong';
}

/** Une production BEHAVIOR (contexte comportemental + pattern). */
export interface OnboardingBehavior {
  readonly context: BehaviorContext;
  readonly pattern: BehaviorPattern;
}

/** Une production GUARDRAIL (code + sévérité + portée — appartiennent à l'evidence). */
export interface OnboardingGuardrail {
  readonly code: GuardrailCode;
  readonly severity: GuardrailSeverity;
  readonly guardrailScope: GuardrailScope;
  /**
   * Contexte DÉCLARÉ du guardrail (lot A ter, correction arbitrage guardrail). Le stem
   * fait foi : Q18 = « le type de SURPRISE que je détesterais » → context 'surprise'. La
   * consolidation ne l'élargit jamais ; un GRD contextuel ne devient pas un GRD global.
   */
  readonly context: EvidenceContext;
}

/** Une production PREFERENCE (chemin + valeur ; detail = verbatim complet du doc). */
export interface OnboardingPreference {
  readonly path: PreferencePath;
  readonly value: string;
  readonly detail: string;
}

/** Un FACT conservé par une option (couche amont — ne produit pas forcément de signal). */
export interface OnboardingFact {
  readonly fact_type: string;
  readonly value?: string;
  readonly subject?: string;
  readonly relation?: string;
  readonly effect?: string;
  readonly user_confirmed: boolean;
  readonly implication?: string;
  /** Verbatim complet de la ligne `facts` du document (lossless). */
  readonly detail: string;
}

/** Un mapping = une option d'onboarding et toutes ses productions par famille. */
export interface OnboardingMapping {
  readonly optionRef: string;
  readonly questionCode: string;
  readonly questionText: string;
  readonly optionText: string;
  readonly domain: string;
  readonly status: OnboardingStatus;
  readonly destination?: string;
  readonly profileEvidences: readonly OnboardingProfileEvidence[];
  readonly affectionLanguage: readonly OnboardingAffection[];
  readonly needs: readonly NeedCode[];
  readonly drivers: readonly DriverCode[];
  readonly behavior?: OnboardingBehavior;
  readonly guardrails: readonly OnboardingGuardrail[];
  readonly preferences: readonly OnboardingPreference[];
  readonly facts: readonly OnboardingFact[];
  readonly affectionCadence?: AffectionCadence;
  /** Information conservée pour le portrait visible (null = non-choix, ex. option 79). */
  readonly retainedInformation: string | null;
}


export const ONBOARDING_MAPPINGS: readonly OnboardingMapping[] = [
  {
    optionRef: "1",
    questionCode: "q1",
    questionText: "Je me sens le plus aimé(e) quand …",
    optionText: "On me dit des mots sincères",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "receive", modality: "WORDS", code: "AFFECTION_RECEIVE_WORDS", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "mots sincères comme modalité affective",
  },
  {
    optionRef: "2",
    questionCode: "q1",
    questionText: "Je me sens le plus aimé(e) quand …",
    optionText: "On m'aide concrètement sans que je demande",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "receive", modality: "SERVICES", code: "AFFECTION_RECEIVE_SERVICES", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_ANTICIPATION"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "aide concrète anticipée",
  },
  {
    optionRef: "3",
    questionCode: "q1",
    questionText: "Je me sens le plus aimé(e) quand …",
    optionText: "On me fait un cadeau pensé spécialement pour moi",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "secondary", context: "gift" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "PERSONALIZED_GIFT", code: "AFFECTION_RECEIVE_PERSONALIZED_GIFT", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_PERSONALIZATION"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "cadeau pensé spécialement pour la personne",
  },
  {
    optionRef: "4",
    questionCode: "q1",
    questionText: "Je me sens le plus aimé(e) quand …",
    optionText: "On me fait un cadeau chargé de sens",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "secondary", context: "gift" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "SYMBOLIC_GIFT", code: "AFFECTION_RECEIVE_SYMBOLIC_GIFT", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_SYMBOLISM"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "valeur symbolique du cadeau",
  },
  {
    optionRef: "5",
    questionCode: "q1",
    questionText: "Je me sens le plus aimé(e) quand …",
    optionText: "On me consacre un vrai moment de qualité",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_EXPERIENCE", value: 1, evidence_role: "secondary", context: "attention_received" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "QUALITY_TIME", code: "AFFECTION_RECEIVE_QUALITY_TIME", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_SHARED_EXPERIENCE"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "temps de qualité partagé",
  },
  {
    optionRef: "6",
    questionCode: "q1",
    questionText: "Je me sens le plus aimé(e) quand …",
    optionText: "On pense à moi dans les petits détails du quotidien",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "receive", modality: "MICRO_ATTENTIONS", code: "AFFECTION_RECEIVE_MICRO_ATTENTIONS", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_ATTENTIVENESS"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "micro-attentions / détails du quotidien",
  },
  {
    optionRef: "7",
    questionCode: "q1",
    questionText: "Je me sens le plus aimé(e) quand …",
    optionText: "On me surprend avec quelque chose d'inattendu",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "receive", modality: "SURPRISE", code: "AFFECTION_RECEIVE_SURPRISE", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_SURPRISE"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "surprise inattendue",
  },
  {
    optionRef: "8",
    questionCode: "q2",
    questionText: "Une attention réussie, pour moi, c'est surtout …",
    optionText: "Quelque chose qui montre qu'on m'a écouté(e)",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_ATTENTIVENESS"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "importance de l'écoute",
  },
  {
    optionRef: "9",
    questionCode: "q2",
    questionText: "Une attention réussie, pour moi, c'est surtout …",
    optionText: "Quelque chose qui tombe au bon moment",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_TIMING"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "importance du timing",
  },
  {
    optionRef: "10",
    questionCode: "q2",
    questionText: "Une attention réussie, pour moi, c'est surtout …",
    optionText: "Quelque chose qui crée un souvenir",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_EXPERIENCE", value: 1, evidence_role: "secondary", context: "attention_received" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_MEMORY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "souvenir créé",
  },
  {
    optionRef: "11",
    questionCode: "q2",
    questionText: "Une attention réussie, pour moi, c'est surtout …",
    optionText: "Quelque chose qui me facilite vraiment la vie",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_FUNCTIONAL", value: 1, evidence_role: "secondary", context: "attention_received" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_RELIEF", "DRV_UTILITY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "facilite concrètement la vie",
  },
  {
    optionRef: "12",
    questionCode: "q2",
    questionText: "Une attention réussie, pour moi, c'est surtout …",
    optionText: "Quelque chose de simple mais sincère",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_AUTHENTICITY", value: 1, evidence_role: "secondary", context: "attention_received" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_SIMPLICITY", "DRV_AUTHENTICITY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "simplicité et sincérité",
  },
  {
    optionRef: "13",
    questionCode: "q2",
    questionText: "Une attention réussie, pour moi, c'est surtout …",
    optionText: "Quelque chose que je n'avais pas vu venir",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_SURPRISE"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "effet de surprise",
  },
  {
    optionRef: "14",
    questionCode: "q2",
    questionText: "Une attention réussie, pour moi, c'est surtout …",
    optionText: "Quelque chose de beau, choisi avec goût",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_AESTHETIC", value: 2, evidence_role: "primary", context: "attention_received" },
      { construct: "PROFILE_SENSITIVITY", facet: "aesthetic", value: 1, evidence_role: "primary", context: "attention_received" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_AESTHETIC"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "beau et goût du choix",
  },
  {
    optionRef: "15",
    questionCode: "q3",
    questionText: "Ce qui me touche le plus durablement …",
    optionText: "Une phrase qui reste en tête",
    domain: "attention reçue",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ce qui dure : les mots",
  },
  {
    optionRef: "16",
    questionCode: "q3",
    questionText: "Ce qui me touche le plus durablement …",
    optionText: "Un geste fait sans bruit, mais au bon moment",
    domain: "attention reçue",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ce qui dure : le geste discret et bien timé",
  },
  {
    optionRef: "17",
    questionCode: "q3",
    questionText: "Ce qui me touche le plus durablement …",
    optionText: "Un objet qui a une histoire",
    domain: "attention reçue",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ce qui dure : l'objet qui a une histoire",
  },
  {
    optionRef: "18",
    questionCode: "q3",
    questionText: "Ce qui me touche le plus durablement …",
    optionText: "Une expérience partagée dont on reparlera longtemps",
    domain: "attention reçue",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ce qui dure : l'expérience partagée",
  },
  {
    optionRef: "19",
    questionCode: "q3",
    questionText: "Ce qui me touche le plus durablement …",
    optionText: "Une surprise parfaitement pensée",
    domain: "attention reçue",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ce qui dure : la surprise bien préparée",
  },
  {
    optionRef: "20",
    questionCode: "q3",
    questionText: "Ce qui me touche le plus durablement …",
    optionText: "Une aide concrète quand j'en ai vraiment besoin",
    domain: "attention reçue",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ce qui dure : l'aide concrète dans la difficulté",
  },
  {
    optionRef: "21",
    questionCode: "q3",
    questionText: "Ce qui me touche le plus durablement …",
    optionText: "Un détail qui prouve qu'on me connaît vraiment",
    domain: "attention reçue",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ce qui dure : le détail qui prouve qu'on la connaît",
  },
  {
    optionRef: "22",
    questionCode: "q4",
    questionText: "Entre deux attentions, je préfère …",
    optionText: "Une petite attention régulière",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "receive", modality: "MICRO_ATTENTIONS", code: "AFFECTION_RECEIVE_MICRO_ATTENTIONS", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    affectionCadence: "regular_micro",
    retainedInformation: "préférence pour les petites attentions régulières",
  },
  {
    optionRef: "23",
    questionCode: "q4",
    questionText: "Entre deux attentions, je préfère …",
    optionText: "Un grand moment rare mais marquant",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_EXPERIENCE", value: 1, evidence_role: "secondary", context: "attention_received" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "QUALITY_TIME", code: "AFFECTION_RECEIVE_QUALITY_TIME", evidence_role: "secondary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    affectionCadence: "rare_marking",
    retainedInformation: "préférence pour le rare et marquant",
  },
  {
    optionRef: "24",
    questionCode: "q4",
    questionText: "Entre deux attentions, je préfère …",
    optionText: "Une aide concrète quand j'en ai besoin",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_FUNCTIONAL", value: 1, evidence_role: "secondary", context: "attention_received" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "SERVICES", code: "AFFECTION_RECEIVE_SERVICES", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_RELIEF"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "aide concrète",
  },
  {
    optionRef: "25",
    questionCode: "q4",
    questionText: "Entre deux attentions, je préfère …",
    optionText: "Un mot sincère au bon moment",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "receive", modality: "WORDS", code: "AFFECTION_RECEIVE_WORDS", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_TIMING"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "mot sincère au bon moment",
  },
  {
    optionRef: "26",
    questionCode: "q4",
    questionText: "Entre deux attentions, je préfère …",
    optionText: "Un cadeau qui a du sens",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "secondary", context: "gift" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "SYMBOLIC_GIFT", code: "AFFECTION_RECEIVE_SYMBOLIC_GIFT", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_SYMBOLISM"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "cadeau qui a du sens",
  },
  {
    optionRef: "27",
    questionCode: "q4",
    questionText: "Entre deux attentions, je préfère …",
    optionText: "Une surprise qui casse la routine",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_OPENNESS", value: 1, evidence_role: "secondary", context: "surprise" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "SURPRISE", code: "AFFECTION_RECEIVE_SURPRISE", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_SURPRISE"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "surprise et rupture de routine",
  },
  {
    optionRef: "28",
    questionCode: "q4",
    questionText: "Entre deux attentions, je préfère …",
    optionText: "Un objet choisi vraiment en fonction de moi et de mes goûts",
    domain: "attention reçue",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "secondary", context: "gift" },
      { construct: "PROFILE_EXACTINGNESS", value: 1, evidence_role: "secondary", context: "gift" },
    ],
    affectionLanguage: [
      { direction: "receive", modality: "PERSONALIZED_GIFT", code: "AFFECTION_RECEIVE_PERSONALIZED_GIFT", evidence_role: "primary" },
    ],
    needs: [],
    drivers: ["DRV_PERSONALIZATION"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "objet précisément choisi",
  },
  {
    optionRef: "29",
    questionCode: "qe",
    questionText: "Et toi, comment montres-tu naturellement ton attention aux autres ?",
    optionText: "Je dis ce que je ressens, je complimente, je rassure",
    domain: "attention donnée",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "give", modality: "WORDS", code: "AFFECTION_GIVE_WORDS", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "donne par les mots",
  },
  {
    optionRef: "30",
    questionCode: "qe",
    questionText: "Et toi, comment montres-tu naturellement ton attention aux autres ?",
    optionText: "J'aide, je rends service sans qu'on me le demande",
    domain: "attention donnée",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "give", modality: "SERVICES", code: "AFFECTION_GIVE_SERVICES", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "donne par les services",
  },
  {
    optionRef: "31",
    questionCode: "qe",
    questionText: "Et toi, comment montres-tu naturellement ton attention aux autres ?",
    optionText: "J'offre des cadeaux choisis avec soin",
    domain: "attention donnée",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "give", modality: "PERSONALIZED_GIFT", code: "AFFECTION_GIVE_PERSONALIZED_GIFT", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "donne par les cadeaux personnalisés",
  },
  {
    optionRef: "32",
    questionCode: "qe",
    questionText: "Et toi, comment montres-tu naturellement ton attention aux autres ?",
    optionText: "J'offre des choses qui ont du sens, une histoire",
    domain: "attention donnée",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "give", modality: "SYMBOLIC_GIFT", code: "AFFECTION_GIVE_SYMBOLIC_GIFT", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "donne par le symbolique",
  },
  {
    optionRef: "33",
    questionCode: "qe",
    questionText: "Et toi, comment montres-tu naturellement ton attention aux autres ?",
    optionText: "Je passe du vrai temps de qualité avec les gens",
    domain: "attention donnée",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_RELATIONALITY", value: 1, evidence_role: "secondary", context: "affection_given" },
    ],
    affectionLanguage: [
      { direction: "give", modality: "QUALITY_TIME", code: "AFFECTION_GIVE_QUALITY_TIME", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "donne par le temps partagé",
  },
  {
    optionRef: "34",
    questionCode: "qe",
    questionText: "Et toi, comment montres-tu naturellement ton attention aux autres ?",
    optionText: "J'ai mille petites attentions au quotidien",
    domain: "attention donnée",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "give", modality: "MICRO_ATTENTIONS", code: "AFFECTION_GIVE_MICRO_ATTENTIONS", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "donne par les micro-attentions",
  },
  {
    optionRef: "35",
    questionCode: "qe",
    questionText: "Et toi, comment montres-tu naturellement ton attention aux autres ?",
    optionText: "J'aime faire des surprises",
    domain: "attention donnée",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [
      { direction: "give", modality: "SURPRISE", code: "AFFECTION_GIVE_SURPRISE", evidence_role: "primary" },
    ],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "donne par les surprises",
  },
  {
    optionRef: "36",
    questionCode: "q5",
    questionText: "Quand je recharge mes batteries…",
    optionText: "J'ai besoin de moments seul(e)",
    domain: "énergie sociale",
    status: "ACTIF",
    profileEvidences: [
      { construct: "SOCIAL_ENERGY", value: 0, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "recharge par solitude",
  },
  {
    optionRef: "37",
    questionCode: "q5",
    questionText: "Quand je recharge mes batteries…",
    optionText: "Je préfère les petits groupes",
    domain: "énergie sociale",
    status: "ACTIF",
    profileEvidences: [
      { construct: "SOCIAL_ENERGY", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "recharge en petit comité",
  },
  {
    optionRef: "38",
    questionCode: "q5",
    questionText: "Quand je recharge mes batteries…",
    optionText: "Ça dépend des jours",
    domain: "énergie sociale",
    status: "ACTIF",
    profileEvidences: [
      { construct: "SOCIAL_ENERGY", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "énergie variable selon les jours",
  },
  {
    optionRef: "39",
    questionCode: "q5",
    questionText: "Quand je recharge mes batteries…",
    optionText: "J'aime être entouré(e)",
    domain: "énergie sociale",
    status: "ACTIF",
    profileEvidences: [
      { construct: "SOCIAL_ENERGY", value: 3, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "recharge par lien social",
  },
  {
    optionRef: "40",
    questionCode: "q5",
    questionText: "Quand je recharge mes batteries…",
    optionText: "Plus c'est animé, mieux c'est",
    domain: "énergie sociale",
    status: "ACTIF",
    profileEvidences: [
      { construct: "SOCIAL_ENERGY", value: 4, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "recharge par stimulation",
  },
  {
    optionRef: "41",
    questionCode: "q6",
    questionText: "Quand je suis stressé(e), j'ai tendance à…",
    optionText: "Garder pour moi, faire bonne figure",
    domain: "stress",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "stress_response", pattern: "internalize" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "sous stress, intériorise",
  },
  {
    optionRef: "42",
    questionCode: "q6",
    questionText: "Quand je suis stressé(e), j'ai tendance à…",
    optionText: "Me retirer, avoir besoin de calme",
    domain: "stress",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_RHYTHM_RESPECT"],
    drivers: [],
    behavior: { context: "stress_response", pattern: "withdraw_seek_calm" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "sous stress, se retire — besoin de calme",
  },
  {
    optionRef: "43",
    questionCode: "q6",
    questionText: "Quand je suis stressé(e), j'ai tendance à…",
    optionText: "En parler, me confier",
    domain: "stress",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_RELATIONALITY", value: 1, evidence_role: "secondary", context: "stress" },
    ],
    affectionLanguage: [],
    needs: ["NEED_SUPPORT"],
    drivers: [],
    behavior: { context: "stress_response", pattern: "confide" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "sous stress, se confie",
  },
  {
    optionRef: "44",
    questionCode: "q6",
    questionText: "Quand je suis stressé(e), j'ai tendance à…",
    optionText: "Agir, me mettre en mouvement",
    domain: "stress",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "stress_response", pattern: "take_action" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "sous stress, agit",
  },
  {
    optionRef: "45",
    questionCode: "q6",
    questionText: "Quand je suis stressé(e), j'ai tendance à…",
    optionText: "Chercher à contrôler ce que je peux",
    domain: "stress",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_MASTERY", value: 2, evidence_role: "secondary", context: "stress" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "stress_response", pattern: "regain_control" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "sous stress, cherche à reprendre la main",
  },
  {
    optionRef: "46",
    questionCode: "q7",
    questionText: "Face à un désaccord, je…",
    optionText: "En parle directement",
    domain: "conflit",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "conflict_response", pattern: "address_directly" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "conflit, aborde directement",
  },
  {
    optionRef: "47",
    questionCode: "q7",
    questionText: "Face à un désaccord, je…",
    optionText: "Ai besoin de temps avant d'en parler",
    domain: "conflit",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_RHYTHM_RESPECT"],
    drivers: [],
    behavior: { context: "conflict_response", pattern: "pause_before_responding" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "conflit, besoin de temps avant d'en parler",
  },
  {
    optionRef: "48",
    questionCode: "q7",
    questionText: "Face à un désaccord, je…",
    optionText: "Évite le conflit autant que possible",
    domain: "conflit",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "conflict_response", pattern: "avoid_conflict" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "évitement du conflit",
  },
  {
    optionRef: "49",
    questionCode: "q7",
    questionText: "Face à un désaccord, je…",
    optionText: "Dédramatise avec l'humour",
    domain: "conflit",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "conflict_response", pattern: "use_humor_to_defuse" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "utilise l'humour dans le conflit",
  },
  {
    optionRef: "50",
    questionCode: "q7",
    questionText: "Face à un désaccord, je…",
    optionText: "Écris plus facilement que je ne parle",
    domain: "conflit",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "conflict_response", pattern: "prefers_writing" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "préfère l'écrit en situation de conflit",
  },
  {
    optionRef: "51",
    questionCode: "q8",
    questionText: "Dans une relation, ce dont j'ai le plus besoin…",
    optionText: "De stabilité et de constance",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_REASSURANCE", "NEED_TRUST"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "besoin relationnel de stabilité, constance, fiabilité",
  },
  {
    optionRef: "52",
    questionCode: "q8",
    questionText: "Dans une relation, ce dont j'ai le plus besoin…",
    optionText: "De liberté et d'espace",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_AUTONOMY", value: 2, evidence_role: "primary", context: "relationship" },
    ],
    affectionLanguage: [],
    needs: ["NEED_FREEDOM", "NEED_RHYTHM_RESPECT"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "liberté et espace relationnel",
  },
  {
    optionRef: "53",
    questionCode: "q8",
    questionText: "Dans une relation, ce dont j'ai le plus besoin…",
    optionText: "De profondeur et d'échanges vrais",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_RELATIONALITY", value: 2, evidence_role: "primary", context: "relationship" },
      { construct: "IMPORTANCE_AUTHENTICITY", value: 1, evidence_role: "primary", context: "relationship" },
    ],
    affectionLanguage: [],
    needs: ["NEED_CONNECTION"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "profondeur et échanges vrais",
  },
  {
    optionRef: "54",
    questionCode: "q8",
    questionText: "Dans une relation, ce dont j'ai le plus besoin…",
    optionText: "De légèreté et de rire",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_LIGHTNESS"],
    drivers: ["DRV_PLAYFULNESS"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "légèreté et rire",
  },
  {
    optionRef: "55",
    questionCode: "q8",
    questionText: "Dans une relation, ce dont j'ai le plus besoin…",
    optionText: "De loyauté dans les moments difficiles",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_RELATIONALITY", value: 1, evidence_role: "primary", context: "relationship" },
    ],
    affectionLanguage: [],
    needs: ["NEED_TRUST", "NEED_SUPPORT"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "loyauté dans la difficulté",
  },
  {
    optionRef: "56",
    questionCode: "q8",
    questionText: "Dans une relation, ce dont j'ai le plus besoin…",
    optionText: "De respect de mon rythme",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_AUTONOMY", value: 1, evidence_role: "primary", context: "relationship" },
    ],
    affectionLanguage: [],
    needs: ["NEED_RHYTHM_RESPECT"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "respect du rythme",
  },
  {
    optionRef: "57",
    questionCode: "q9",
    questionText: "Pour communiquer, je préfère…",
    optionText: "Aller droit au but",
    domain: "communication",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.style", value: "direct", detail: "PREFERENCE.communication.style = direct" },
    ],
    facts: [],
    retainedInformation: "communication directe",
  },
  {
    optionRef: "58",
    questionCode: "q9",
    questionText: "Pour communiquer, je préfère…",
    optionText: "Parler de ce que je ressens",
    domain: "communication",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.style", value: "expressive", detail: "PREFERENCE.communication.style = expressive" },
    ],
    facts: [],
    retainedInformation: "communication centrée sur l'expression des ressentis",
  },
  {
    optionRef: "59",
    questionCode: "q9",
    questionText: "Pour communiquer, je préfère…",
    optionText: "Tout analyser en profondeur",
    domain: "communication",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_REFLECTIVENESS", value: 2, evidence_role: "primary", context: "communication" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.style", value: "analytical", detail: "PREFERENCE.communication.style = analytical" },
    ],
    facts: [],
    retainedInformation: "communication analytique et approfondie",
  },
  {
    optionRef: "60",
    questionCode: "q9",
    questionText: "Pour communiquer, je préfère…",
    optionText: "Garder ça léger, avec humour",
    domain: "communication",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.style", value: "light_humorous", detail: "PREFERENCE.communication.style = light_humorous" },
    ],
    facts: [],
    retainedInformation: "communication légère et humoristique",
  },
  {
    optionRef: "61",
    questionCode: "q9",
    questionText: "Pour communiquer, je préfère…",
    optionText: "Écrire plutôt que parler",
    domain: "communication",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.channel", value: "written", detail: "PREFERENCE.communication.channel = written   (contexte self_expression · evidence de confirmation, poids non doublé)" },
    ],
    facts: [],
    retainedInformation: "canal écrit préféré",
  },
  {
    optionRef: "62",
    questionCode: "q10",
    questionText: "Pour mes grandes décisions, je…",
    optionText: "Analyse les pour et les contre",
    domain: "décision",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_REFLECTIVENESS", value: 1, evidence_role: "primary", context: "decision" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "decision_process", pattern: "weigh_pros_and_cons" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "décision rationnelle, analyse avantages-inconvénients",
  },
  {
    optionRef: "63",
    questionCode: "q10",
    questionText: "Pour mes grandes décisions, je…",
    optionText: "Fais confiance à mon instinct",
    domain: "décision",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "decision_process", pattern: "trust_instinct" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "décision intuitive",
  },
  {
    optionRef: "64",
    questionCode: "q10",
    questionText: "Pour mes grandes décisions, je…",
    optionText: "Demande l'avis des proches",
    domain: "décision",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_RELATIONALITY", value: 1, evidence_role: "primary", context: "decision" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "decision_process", pattern: "consult_close_ones" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "décision consultative, avis des proches",
  },
  {
    optionRef: "65",
    questionCode: "q10",
    questionText: "Pour mes grandes décisions, je…",
    optionText: "Fais des recherches approfondies",
    domain: "décision",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_REFLECTIVENESS", value: 2, evidence_role: "primary", context: "decision" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "decision_process", pattern: "research_thoroughly" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "recherches approfondies, décision documentée",
  },
  {
    optionRef: "66",
    questionCode: "q10",
    questionText: "Pour mes grandes décisions, je…",
    optionText: "Attends que ce soit clair en moi",
    domain: "décision",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_REFLECTIVENESS", value: 1, evidence_role: "primary", context: "decision" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "decision_process", pattern: "wait_for_inner_clarity" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "décision par maturation",
  },
  {
    optionRef: "67",
    questionCode: "q11",
    questionText: "J'exprime mes émotions…",
    optionText: "Assez librement",
    domain: "émotions",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "emotional_expression", pattern: "openly" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "expression émotionnelle libre",
  },
  {
    optionRef: "68",
    questionCode: "q11",
    questionText: "J'exprime mes émotions…",
    optionText: "Avec quelques personnes de confiance",
    domain: "émotions",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "emotional_expression", pattern: "with_trusted_few" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "expression émotionnelle sélective, cercle de confiance",
  },
  {
    optionRef: "69",
    questionCode: "q11",
    questionText: "J'exprime mes émotions…",
    optionText: "Par mes actes plus que par mes mots",
    domain: "émotions",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "emotional_expression", pattern: "through_actions" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "expression émotionnelle par les actes",
  },
  {
    optionRef: "70",
    questionCode: "q11",
    questionText: "J'exprime mes émotions…",
    optionText: "Rarement, je préfère garder ça pour moi",
    domain: "émotions",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "emotional_expression", pattern: "rarely_keeps_private" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "expression émotionnelle réservée",
  },
  {
    optionRef: "71",
    questionCode: "q11",
    questionText: "J'exprime mes émotions…",
    optionText: "Souvent après coup",
    domain: "émotions",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    behavior: { context: "emotional_expression", pattern: "delayed" },
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "expression émotionnelle différée, compréhension après coup",
  },
  {
    optionRef: "72",
    questionCode: "q12",
    questionText: "Quand quelqu'un m'invite ou m'offre quelque chose…",
    optionText: "N'importe quelle attention sincère me touche",
    domain: "cadeau et invitation",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [
      { construct: "IMPORTANCE_AUTHENTICITY", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "la sincérité avant tout",
  },
  {
    optionRef: "73",
    questionCode: "q12",
    questionText: "Quand quelqu'un m'invite ou m'offre quelque chose…",
    optionText: "Quelque chose de bien choisi, même simple",
    domain: "cadeau et invitation",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [
      { construct: "PROFILE_EXACTINGNESS", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "justesse du choix",
  },
  {
    optionRef: "74",
    questionCode: "q12",
    questionText: "Quand quelqu'un m'invite ou m'offre quelque chose…",
    optionText: "Un certain niveau de qualité compte pour moi",
    domain: "cadeau et invitation",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [
      { construct: "PROFILE_EXACTINGNESS", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "un niveau de qualité compte",
  },
  {
    optionRef: "75",
    questionCode: "q12",
    questionText: "Quand quelqu'un m'invite ou m'offre quelque chose…",
    optionText: "Les détails influencent beaucoup mon expérience",
    domain: "cadeau et invitation",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [
      { construct: "PROFILE_SENSITIVITY", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "les détails pèsent sur l'expérience",
  },
  {
    optionRef: "76",
    questionCode: "q12",
    questionText: "Quand quelqu'un m'invite ou m'offre quelque chose…",
    optionText: "Pas de préférence, je n'y suis pas attaché(e)",
    domain: "cadeau et invitation",
    status: "REMOVED_FROM_ONBOARDING_CORE",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "faible exigence sur la forme",
  },
  {
    optionRef: "77",
    questionCode: "q13",
    questionText: "Pour les cadeaux, je préfère…",
    optionText: "Des expériences",
    domain: "cadeau",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_EXPERIENCE", value: 2, evidence_role: "primary", context: "gift" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "préférence cadeaux-expériences",
  },
  {
    optionRef: "78",
    questionCode: "q13",
    questionText: "Pour les cadeaux, je préfère…",
    optionText: "Des objets à garder",
    domain: "cadeau",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_OBJECT", value: 2, evidence_role: "primary", context: "gift" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "préférence cadeaux-objets",
  },
  {
    optionRef: "79",
    questionCode: "q13",
    questionText: "Pour les cadeaux, je préfère…",
    optionText: "Les deux me touchent",
    domain: "cadeau",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: null,
  },
  {
    optionRef: "80",
    questionCode: "q13",
    questionText: "Pour les cadeaux, je préfère…",
    optionText: "Des choses utiles",
    domain: "cadeau",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_FUNCTIONAL", value: 2, evidence_role: "primary", context: "gift" },
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "primary", context: "gift" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_UTILITY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "préférence cadeau utile",
  },
  {
    optionRef: "81",
    questionCode: "q13",
    questionText: "Pour les cadeaux, je préfère…",
    optionText: "Des choses symboliques",
    domain: "cadeau",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "primary", context: "gift" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_SYMBOLISM"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "préférence pour les cadeaux symboliques",
  },
  {
    optionRef: "82",
    questionCode: "q14",
    questionText: "Pour les cadeaux matériels, ce qui me touche le plus…",
    optionText: "Un objet utile et bien pensé",
    domain: "cadeau matériel",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_FUNCTIONAL", value: 2, evidence_role: "primary", context: "gift.material" },
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "primary", context: "gift.material" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_UTILITY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "objet utile, intelligence d'usage",
  },
  {
    optionRef: "83",
    questionCode: "q14",
    questionText: "Pour les cadeaux matériels, ce qui me touche le plus…",
    optionText: "Quelque chose qui montre qu'on m'a écouté(e)",
    domain: "cadeau matériel",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_ATTENTIVENESS"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "cadeau fondé sur l'écoute",
  },
  {
    optionRef: "84",
    questionCode: "q14",
    questionText: "Pour les cadeaux matériels, ce qui me touche le plus…",
    optionText: "Un objet beau et de qualité",
    domain: "cadeau matériel",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_AESTHETIC", value: 2, evidence_role: "primary", context: "gift.material" },
      { construct: "PROFILE_EXACTINGNESS", value: 1, evidence_role: "primary", context: "gift.material" },
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "primary", context: "gift.material" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_AESTHETIC", "DRV_QUALITY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "beau et qualité",
  },
  {
    optionRef: "85",
    questionCode: "q14",
    questionText: "Pour les cadeaux matériels, ce qui me touche le plus…",
    optionText: "Un objet de valeur symbolique",
    domain: "cadeau matériel",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_OBJECT", value: 1, evidence_role: "primary", context: "gift.material" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_SYMBOLISM"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "valeur symbolique",
  },
  {
    optionRef: "86",
    questionCode: "q14",
    questionText: "Pour les cadeaux matériels, ce qui me touche le plus…",
    optionText: "Je préfère les expériences aux objets",
    domain: "cadeau matériel",
    status: "ACTIF",
    profileEvidences: [
      { construct: "APPETENCE_EXPERIENCE", value: 2, evidence_role: "primary", context: "gift.material" },
      { construct: "APPETENCE_OBJECT", value: -1, evidence_role: "primary", context: "gift.material" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "préférence comparative explicite : expérience avant objet",
  },
  {
    optionRef: "87",
    questionCode: "q15",
    questionText: "Ma relation à la nourriture et aux restaurants…",
    optionText: "J'aime manger partout",
    domain: "table",
    status: "MOVED_TO_DISCOVERY_FOOD",
    destination: "Discovery Food",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "ouverte sur différents types de tables",
  },
  {
    optionRef: "88",
    questionCode: "q15",
    questionText: "Ma relation à la nourriture et aux restaurants…",
    optionText: "Je suis gourmand(e)",
    domain: "table",
    status: "MOVED_TO_DISCOVERY_FOOD",
    destination: "Discovery Food",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "gourmandise",
  },
  {
    optionRef: "89",
    questionCode: "q15",
    questionText: "Ma relation à la nourriture et aux restaurants…",
    optionText: "J'adore les belles tables",
    domain: "table",
    status: "MOVED_TO_DISCOVERY_FOOD",
    destination: "Discovery Food",
    profileEvidences: [
      { construct: "IMPORTANCE_AESTHETIC", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "aime les belles tables",
  },
  {
    optionRef: "90",
    questionCode: "q15",
    questionText: "Ma relation à la nourriture et aux restaurants…",
    optionText: "La gastronomie est une passion",
    domain: "table",
    status: "MOVED_TO_DISCOVERY_FOOD",
    destination: "Discovery Food",
    profileEvidences: [
      { construct: "PROFILE_INTENSITY", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "gastronomie = passion · INTEREST food_gastronomy, interest_level = passion · contexte food_gastronomy",
  },
  {
    optionRef: "91",
    questionCode: "q15",
    questionText: "Ma relation à la nourriture et aux restaurants…",
    optionText: "Je mange pour vivre",
    domain: "table",
    status: "MOVED_TO_DISCOVERY_FOOD",
    destination: "Discovery Food",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "faible intérêt pour la gastronomie",
  },
  {
    optionRef: "92",
    questionCode: "q16",
    questionText: "Si on m'offre un week-end, ce qui compte le plus…",
    optionText: "La destination avant tout",
    domain: "voyage",
    status: "MOVED_TO_DISCOVERY_VOYAGE",
    destination: "Discovery Voyage",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "destination prioritaire",
  },
  {
    optionRef: "93",
    questionCode: "q16",
    questionText: "Si on m'offre un week-end, ce qui compte le plus…",
    optionText: "Un hôtel confortable et bien situé",
    domain: "voyage",
    status: "MOVED_TO_DISCOVERY_VOYAGE",
    destination: "Discovery Voyage",
    profileEvidences: [
      { construct: "IMPORTANCE_FUNCTIONAL", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "confort et emplacement",
  },
  {
    optionRef: "94",
    questionCode: "q16",
    questionText: "Si on m'offre un week-end, ce qui compte le plus…",
    optionText: "Le charme et l'authenticité",
    domain: "voyage",
    status: "MOVED_TO_DISCOVERY_VOYAGE",
    destination: "Discovery Voyage",
    profileEvidences: [
      { construct: "IMPORTANCE_AUTHENTICITY", value: 2, evidence_role: "primary", context: "GLOBAL" },
      { construct: "IMPORTANCE_AESTHETIC", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "charme et authenticité",
  },
  {
    optionRef: "95",
    questionCode: "q16",
    questionText: "Si on m'offre un week-end, ce qui compte le plus…",
    optionText: "Le luxe et le service",
    domain: "voyage",
    status: "MOVED_TO_DISCOVERY_VOYAGE",
    destination: "Discovery Voyage",
    profileEvidences: [
      { construct: "APPETENCE_PREMIUM", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "luxe et qualité de service",
  },
  {
    optionRef: "96",
    questionCode: "q16",
    questionText: "Si on m'offre un week-end, ce qui compte le plus…",
    optionText: "L'important, c'est d'être ensemble",
    domain: "voyage",
    status: "MOVED_TO_DISCOVERY_VOYAGE",
    destination: "Discovery Voyage",
    profileEvidences: [
      { construct: "PROFILE_RELATIONALITY", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "la compagnie passe avant le lieu",
  },
  {
    optionRef: "97",
    questionCode: "q4a",
    questionText: "Mon rapport au temps et à l'organisation…",
    optionText: "J'anticipe et je planifie à l'avance",
    domain: "temps et organisation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_STRUCTURE", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "anticipe et planifie",
  },
  {
    optionRef: "98",
    questionCode: "q4a",
    questionText: "Mon rapport au temps et à l'organisation…",
    optionText: "Je gère au fil de l'eau",
    domain: "temps et organisation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_STRUCTURE", value: -1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "fonctionne au fil de l'eau",
  },
  {
    optionRef: "99",
    questionCode: "q4a",
    questionText: "Mon rapport au temps et à l'organisation…",
    optionText: "La ponctualité compte beaucoup pour moi",
    domain: "temps et organisation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.relational.punctuality", value: "high", detail: "PREFERENCE.relational.punctuality = high   ·   context = relationnel" },
    ],
    facts: [],
    retainedInformation: "importance forte de la ponctualité",
  },
  {
    optionRef: "100",
    questionCode: "q4a",
    questionText: "Mon rapport au temps et à l'organisation…",
    optionText: "Je suis souvent un peu en retard, sans malice",
    domain: "temps et organisation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [
      { fact_type: "habit", value: "souvent un peu en retard, sans malice", user_confirmed: true, implication: "ne pas bâtir une attention dont la réussite dépend de sa ponctualité", detail: "fact_type = habit   ·   value = « souvent un peu en retard, sans malice »   ·   user_confirmed = true   ·   implication : ne pas bâtir une attention dont la réussite dépend de sa ponctualité" },
    ],
    retainedInformation: "ponctualité personnelle faible",
  },
  {
    optionRef: "101",
    questionCode: "q4a",
    questionText: "Mon rapport au temps et à l'organisation…",
    optionText: "La charge mentale m'épuise vite",
    domain: "temps et organisation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [
      { fact_type: "functional_impact", subject: "mental_load", relation: "causes", effect: "rapid_exhaustion", user_confirmed: true, implication: "réduire le nombre de décisions, coordinations et tâches nécessaires. Ne produit PAS NEED_RELIEF.", detail: "fact_type = functional_impact   ·   subject = mental_load   ·   relation = causes   ·   effect = rapid_exhaustion   ·   user_confirmed = true   ·   implication : réduire le nombre de décisions, coordinations et tâches nécessaires. Ne produit PAS NEED_RELIEF." },
    ],
    retainedInformation: "sensibilité à la charge mentale, coût énergétique de la charge mentale",
  },
  {
    optionRef: "102",
    questionCode: "q4b",
    questionText: "Dans ce que je choisis ou apprécie, qu'est-ce qui te ressemble le plus ?",
    optionText: "La qualité compte, même si je n'en parle pas",
    domain: "qualité et standing",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_EXACTINGNESS", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_QUALITY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "importance discrète de la qualité",
  },
  {
    optionRef: "103",
    questionCode: "q4b",
    questionText: "Dans ce que je choisis ou apprécie, qu'est-ce qui te ressemble le plus ?",
    optionText: "Je préfère la simplicité authentique au luxe",
    domain: "qualité et standing",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_AUTHENTICITY", value: 2, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_SIMPLICITY", "DRV_AUTHENTICITY"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "simplicité authentique",
  },
  {
    optionRef: "104",
    questionCode: "q4b",
    questionText: "Dans ce que je choisis ou apprécie, qu'est-ce qui te ressemble le plus ?",
    optionText: "J'aime le beau et le raffinement",
    domain: "qualité et standing",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_AESTHETIC", value: 2, evidence_role: "primary", context: "GLOBAL" },
      { construct: "PROFILE_SENSITIVITY", facet: "aesthetic", value: 1, evidence_role: "primary", context: "GLOBAL" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: ["DRV_AESTHETIC"],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "beau et raffinement esthétique",
  },
  {
    optionRef: "105",
    questionCode: "q4b",
    questionText: "Dans ce que je choisis ou apprécie, qu'est-ce qui te ressemble le plus ?",
    optionText: "Le prix m'importe peu, c'est l'intention",
    domain: "qualité et standing",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.gift.value_basis", value: "intention_over_price", detail: "PREFERENCE.gift.value_basis = intention_over_price" },
    ],
    facts: [],
    retainedInformation: "le prix n'est pas le critère, importance de l'intention",
  },
  {
    optionRef: "106",
    questionCode: "q4b",
    questionText: "Dans ce que je choisis ou apprécie, qu'est-ce qui te ressemble le plus ?",
    optionText: "Je suis sensible à certaines marques ou maisons",
    domain: "qualité et standing",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.brands.sensitivity", value: "positive", detail: "PREFERENCE.brands.sensitivity = positive   ·   opens_branch = brands   ·   trigger Discovery « lesquelles ? » → ENTITY_BRAND avec relation LOVE | LIKE" },
    ],
    facts: [],
    retainedInformation: "sensibilité déclarée à certaines marques ou maisons",
  },
  {
    optionRef: "106b",
    questionCode: "q4b",
    questionText: "Dans ce que je choisis ou apprécie, qu'est-ce qui te ressemble le plus ?",
    optionText: "Je suis attiré(e) par les lieux ou expériences d'exception",
    domain: "qualité et standing",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.experience.tier", value: "exceptional", detail: "PREFERENCE.experience.tier = exceptional   ·   confidence = low, à préciser par le Discovery" },
    ],
    facts: [],
    retainedInformation: "attrait pour les lieux ou expériences d'exception",
  },
  {
    optionRef: "107",
    questionCode: "q4c",
    questionText: "Quand on organise quelque chose pour moi…",
    optionText: "J'aime tout savoir à l'avance",
    domain: "organisation d'une surprise",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_STRUCTURE", value: 2, evidence_role: "primary", context: "organised_for_me" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.organised_for_me.surprise_level", value: "none", detail: "PREFERENCE.organised_for_me.surprise_level = none" },
    ],
    facts: [],
    retainedInformation: "fort besoin d'information préalable quand quelqu'un organise pour soi",
  },
  {
    optionRef: "108",
    questionCode: "q4c",
    questionText: "Quand on organise quelque chose pour moi…",
    optionText: "J'aime garder une part de surprise",
    domain: "organisation d'une surprise",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.organised_for_me.surprise_level", value: "partial", detail: "PREFERENCE.organised_for_me.surprise_level = partial" },
    ],
    facts: [],
    retainedInformation: "surprise cadrée, partielle",
  },
  {
    optionRef: "109",
    questionCode: "q4c",
    questionText: "Quand on organise quelque chose pour moi…",
    optionText: "J'aime être totalement surpris(e)",
    domain: "organisation d'une surprise",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.organised_for_me.surprise_level", value: "full", detail: "PREFERENCE.organised_for_me.surprise_level = full" },
    ],
    facts: [],
    retainedInformation: "surprise totale appréciée",
  },
  {
    optionRef: "110",
    questionCode: "q4c",
    questionText: "Quand on organise quelque chose pour moi…",
    optionText: "J'ai besoin de valider les détails",
    domain: "organisation d'une surprise",
    status: "ACTIF",
    profileEvidences: [
      { construct: "IMPORTANCE_MASTERY", value: 2, evidence_role: "primary", context: "organised_for_me" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "besoin de valider personnellement les paramètres",
  },
  {
    optionRef: "111",
    questionCode: "q4c",
    questionText: "Quand on organise quelque chose pour moi…",
    optionText: "Je m'adapte facilement",
    domain: "organisation d'une surprise",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_ADAPTABILITY", value: 2, evidence_role: "primary", context: "organised_for_me" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "flexibilité, adaptation facile",
  },
  {
    optionRef: "112",
    questionCode: "q4d",
    questionText: "Pour rester en contact, je préfère…",
    optionText: "Un appel téléphonique",
    domain: "canal de contact",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.channel", value: "call", detail: "PREFERENCE.communication.channel = call   ·   stability = stable" },
    ],
    facts: [],
    retainedInformation: "canal de contact = appel",
  },
  {
    optionRef: "113",
    questionCode: "q4d",
    questionText: "Pour rester en contact, je préfère…",
    optionText: "Un message écrit",
    domain: "canal de contact",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.channel", value: "written", detail: "PREFERENCE.communication.channel = written   ·   stability = stable" },
    ],
    facts: [],
    retainedInformation: "canal de contact = écrit",
  },
  {
    optionRef: "114",
    questionCode: "q4d",
    questionText: "Pour rester en contact, je préfère…",
    optionText: "Un vocal",
    domain: "canal de contact",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.channel", value: "voice", detail: "PREFERENCE.communication.channel = voice   ·   stability = stable" },
    ],
    facts: [],
    retainedInformation: "canal de contact = vocal",
  },
  {
    optionRef: "115",
    questionCode: "q4d",
    questionText: "Pour rester en contact, je préfère…",
    optionText: "En personne, rien ne remplace",
    domain: "canal de contact",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.channel", value: "in_person", detail: "PREFERENCE.communication.channel = in_person   ·   stability = stable" },
    ],
    facts: [],
    retainedInformation: "canal de contact = présentiel",
  },
  {
    optionRef: "116",
    questionCode: "q4d",
    questionText: "Pour rester en contact, je préfère…",
    optionText: "Peu importe, selon le moment",
    domain: "canal de contact",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [
      { path: "PREFERENCE.communication.channel", value: "flexible", detail: "PREFERENCE.communication.channel = flexible   ·   stability = contextual" },
    ],
    facts: [],
    retainedInformation: "canal indifférent, selon le moment",
  },
  {
    optionRef: "117",
    questionCode: "q18",
    questionText: "Le type de surprise que je détesterais…",
    optionText: "Une surprise devant beaucoup de monde",
    domain: "surprise",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [
      { code: "GRD_PUBLIC_EXPOSURE", severity: "HARD", guardrailScope: "selection", context: "surprise" },
    ],
    preferences: [],
    facts: [],
    retainedInformation: "éviter la surprise publique",
  },
  {
    optionRef: "118",
    questionCode: "q18",
    questionText: "Le type de surprise que je détesterais…",
    optionText: "Une surprise qui change mon planning",
    domain: "surprise",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_STRUCTURE", value: 1, evidence_role: "secondary", context: "surprise" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [
      { code: "GRD_SCHEDULE_DISRUPTION", severity: "HARD", guardrailScope: "selection", context: "surprise" },
    ],
    preferences: [],
    facts: [],
    retainedInformation: "ne pas bouleverser le planning",
  },
  {
    optionRef: "119",
    questionCode: "q18",
    questionText: "Le type de surprise que je détesterais…",
    optionText: "Une surprise trop intime ou trop intense",
    domain: "surprise",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [
      { code: "GRD_TOO_INTIMATE", severity: "HARD", guardrailScope: "selection", context: "surprise" },
      { code: "GRD_SENTIMENTAL_OVERLOAD", severity: "HARD", guardrailScope: "selection", context: "surprise" },
    ],
    preferences: [],
    facts: [],
    retainedInformation: "éviter la surprise trop intime ou émotionnellement intense",
  },
  {
    optionRef: "120",
    questionCode: "q18",
    questionText: "Le type de surprise que je détesterais…",
    optionText: "Une surprise mal organisée",
    domain: "surprise",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_EXACTINGNESS", value: 1, evidence_role: "secondary", context: "surprise" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [
      { code: "GRD_POOR_EXECUTION", severity: "HARD", guardrailScope: "execution", context: "surprise" },
    ],
    preferences: [],
    facts: [],
    retainedInformation: "mauvaise exécution = risque fort d'échec",
  },
  {
    optionRef: "121",
    questionCode: "q18",
    questionText: "Le type de surprise que je détesterais…",
    optionText: "Je suis plutôt partant(e) pour tout",
    domain: "surprise",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_ADAPTABILITY", value: 1, evidence_role: "primary", context: "surprise" },
    ],
    affectionLanguage: [],
    needs: [],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "forte ouverture aux formats de surprise",
  },
  {
    optionRef: "122",
    questionCode: "q19",
    questionText: "Ce qui me blesse le plus dans une relation…",
    optionText: "Ne pas être écouté(e)",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_SEEN_UNDERSTOOD"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "blessure liée au manque d'écoute",
  },
  {
    optionRef: "123",
    questionCode: "q19",
    questionText: "Ce qui me blesse le plus dans une relation…",
    optionText: "Être oublié(e) ou mis(e) de côté",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_LOVED_MATTER", "NEED_CHOSEN"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "blessure liée à l'oubli ou l'exclusion",
  },
  {
    optionRef: "124",
    questionCode: "q19",
    questionText: "Ce qui me blesse le plus dans une relation…",
    optionText: "Être envahi(e) ou contrôlé(e)",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_AUTONOMY", value: 2, evidence_role: "primary", context: "relationship" },
    ],
    affectionLanguage: [],
    needs: ["NEED_FREEDOM", "NEED_RHYTHM_RESPECT"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "blessure liée à l'intrusion ou au contrôle",
  },
  {
    optionRef: "125",
    questionCode: "q19",
    questionText: "Ce qui me blesse le plus dans une relation…",
    optionText: "Les reproches ou critiques répétées",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_ACCEPTANCE"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "blessure liée aux critiques répétées",
  },
  {
    optionRef: "126",
    questionCode: "q19",
    questionText: "Ce qui me blesse le plus dans une relation…",
    optionText: "Le manque de fiabilité",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [],
    affectionLanguage: [],
    needs: ["NEED_TRUST", "NEED_REASSURANCE"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "blessure liée à l'inconstance, besoin de fiabilité chez l'autre",
  },
  {
    optionRef: "127",
    questionCode: "q19",
    questionText: "Ce qui me blesse le plus dans une relation…",
    optionText: "Le manque de profondeur",
    domain: "relation",
    status: "ACTIF",
    profileEvidences: [
      { construct: "PROFILE_RELATIONALITY", value: 1, evidence_role: "primary", context: "relationship" },
    ],
    affectionLanguage: [],
    needs: ["NEED_CONNECTION"],
    drivers: [],
    guardrails: [],
    preferences: [],
    facts: [],
    retainedInformation: "blessure liée à la superficialité ou au manque de profondeur",
  },
];


/**
 * Les options ACTIVES — SEULE porte d'entrée du scoring.
 * Les options non actives conservent leurs mappings mais sont exclues ici.
 */
export function activeOptions(): readonly OnboardingMapping[] {
  return ONBOARDING_MAPPINGS.filter((m) => m.status === 'ACTIF');
}

/** Retrouve un mapping par sa référence d'option (ex. "106", "106b"). */
export function mappingByRef(optionRef: string): OnboardingMapping | undefined {
  return ONBOARDING_MAPPINGS.find((m) => m.optionRef === optionRef);
}

/* ────────────────────────────────────────────────────────────────────────
 * LES DEUX QUESTIONS AJOUTÉES (lot A ter, mapping-soutien-moteurs.md v1.0.0).
 * Hors ONBOARDING_MAPPINGS (qui reste le socle verbatim 128/106) : ce sont deux
 * questions nouvelles, mappées ici, consommées par le lot B. Verbatim du document.
 * ──────────────────────────────────────────────────────────────────────── */

/** Une option de `soutien` → un NEED distinct, aucune collision. */
export interface SoutienOption {
  readonly optionText: string;
  readonly need: NeedCode;
}

/**
 * `soutien` — « Quand ça ne va pas, qu'est-ce qui t'aide vraiment ? » (5 options, 2 max).
 * Chaque option → un NEED distinct, en contexte `distress` (LOCAL_CONTEXTUAL, jamais
 * globalisé par cette seule question). Poids ÉGAUX entre options choisies (l'ordre n'est
 * pas sémantique ici). `assertionStatus` dérivé du sourceType à la création (jamais saisi).
 */
export const SOUTIEN = {
  questionCode: 'soutien',
  questionText: 'Quand ça ne va pas, qu’est-ce qui t’aide vraiment ?',
  maxChoices: 2,
  /** Propriétés communes de chaque evidence NEED produite. */
  evidence: { evidence_role: 'primary', strength: 'strong', context: 'distress' } as const,
  options: [
    { optionText: 'Qu’on m’écoute', need: 'NEED_SEEN_UNDERSTOOD' },
    { optionText: 'Qu’on me rassure', need: 'NEED_REASSURANCE' },
    { optionText: 'Qu’on m’aide concrètement', need: 'NEED_RELIEF' },
    { optionText: 'Qu’on reste simplement près de moi', need: 'NEED_SUPPORT' },
    { optionText: 'Qu’on me laisse un peu tranquille', need: 'NEED_RHYTHM_RESPECT' },
  ] satisfies readonly SoutienOption[],
} as const;

/** Une option de `moteurs` → une connaissance ouverte `life_priority`. AUCUN code canonique. */
export interface MoteurOption {
  readonly optionText: string;
  readonly subject: string;
}

/**
 * `moteurs` — « Qu'est-ce qui compte particulièrement pour toi dans ta vie ? » (6 options, 3 max).
 * Produit SIX OpenKnowledge `life_priority`, ZÉRO evidence canonique (ni NEED, ni PROFILE,
 * ni DRIVER, ni AFFECTION) : une priorité de vie n'est pas un besoin psychologique. Le
 * `subject` passe par le résolveur pour obtenir un SubjectId ; le libellé reste en subjectLabel.
 * Double sélection (soin + transmission) = UNE source (indépendance sur sourceType).
 */
export const MOTEURS = {
  questionCode: 'moteurs',
  questionText: 'Qu’est-ce qui compte particulièrement pour toi dans ta vie ?',
  maxChoices: 3,
  /** Propriétés communes de chaque OpenKnowledge produite. */
  openKnowledge: { type: 'life_priority', relation: 'matters_to', intensity: 'strong', context: 'GLOBAL', confidence: 'high' } as const,
  options: [
    { optionText: 'La liberté', subject: 'freedom' },
    { optionText: 'Apprendre et découvrir', subject: 'learning_discovery' },
    { optionText: 'La famille', subject: 'family' },
    { optionText: 'Construire et accomplir', subject: 'building_accomplishment' },
    { optionText: 'Prendre soin des autres', subject: 'caring_for_others' },
    { optionText: 'Contribuer ou transmettre', subject: 'contribution_transmission' },
  ] satisfies readonly MoteurOption[],
} as const;
